### ISSUE TITLE
[ERROR] No tests found, check the SearchPattern in the extension settings

### ISSUE THREAD

**Issue by ffMathy** [Derivitec/vscode-dotnet-adapter#35]
It's for this project: https://github.com/dogger/app.dogger.io

I'm just running it from the root.

Glob pattern is set to: `"**/bin/**/*.Tests.{dll,exe}"`

**Comment by andrewbridge** [comment]
Hi @ffMathy,

Apologies for the delay in getting back to you!

You'll need to remove `"**/bin/": true` from [L5 of your .vscode/settings.json](https://github.com/dogger/app.dogger.io/blob/master/.vscode/settings.json#L5) for the adapter to discover tests correctly. Moving that line into `files.watcherExclude` may mitigate any performance issues that may arise elsewhere in VSCode.

----

**Further details**

Our discovery phase uses the VSCode API to find the necessary binaries (we use the [findFiles method](https://code.visualstudio.com/api/references/vscode-api#2863) in our [file discovery](https://github.com/Derivitec/vscode-dotnet-adapter/blob/b904c27d3662ac251ee50806296a04dfc0fefc88/src/TestDiscovery.ts#L190)). This allows the adapter to run reliably, regardless of how VSCode is being run (remotely, in browser, across platforms etc), however it does also mean the adapter is caught in the confusion of how this method works ([1](https://github.com/Microsoft/vscode/issues/48674), [2](https://github.com/matepek/vscode-catch2-test-adapter/issues/113), [3](https://github.com/microsoft/vscode/issues/77813), [4](https://github.com/microsoft/vscode/issues/101889)).

The `files.exclude` and `search.exclude` settings both have an impact on the files visible to extensions that use this method. Extensions that use file watchers, like ours, are also affected by the `files.watcherExclude` setting. The reason no tests are found in your project is that you are excluding `bin` directories in your `files.exclude` project setting.

It's possible for us to ignore all exclusions except those in the extension `skippattern` setting during the discovery phase, but we're not able to ignore exclusions when setting file watchers. Between that inconsistency and the potential performance hit in big codebases or over slow remote connections, it doesn't seem worthwhile to add an additional override setting to allow this.

I'll add further information and a link to this issue in our readme so this is clear from the outset. Additionally, in diagnosing your issue, I have made a few unrelated fixes to our adapter, so many thanks!

I'll close this issue when I merge in the update to the readme, but feel free to reopen if my suggestion hasn't worked as expected.
